/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.opendcs.shefit;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.antlr.v4.runtime.BailErrorStrategy;
import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.opendcs.shef.parser.*;
import org.opendcs.shef.parser.shefParser.ShefFileContext;

class LibraryTest {    

    private ShefFileContext file;

    @BeforeEach
    public void setup() {
        CharStream stream = CharStreams.fromString(".A TEST 20230318 Z DH010203 /HG 1.0\r\n.A TEST2 0318 Z DH050607 /HG 2.0 : Busted pulley.\r\n");
        shefLexer l = new shefLexer(stream);
        CommonTokenStream tokens = new CommonTokenStream(l);
        shefParser p = new shefParser(tokens);
        p.setTrace(true);
        p.setErrorHandler(new BailErrorStrategy());
        file = p.shefFile();
    }

    @Test
    public void test_visitor() {
        DataSet set = new DataSet();
        ShefFileVisitor visitor = new ShefFileVisitor(set);
        visitor.visitShefFile(file);
        boolean found = false;
        for(ShefRecord r: set.getData()) {
            System.out.println(r);
            if( r.getStation().equals("TEST")) {
                found = true;
            }
        }
        assertTrue(found, "Could not find expected record.");
    }
}
