/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.opendcs.shefit;

import org.opendcs.shef.parser.shefBaseListener;
import org.opendcs.shef.parser.shefParser;

public class shefListener extends shefBaseListener {
    
    @Override
    public void enterShefFile(shefParser.ShefFileContext ctx) {
        System.out.println("Starting shef file.");
    }

    @Override 
    public void exitA_FORMAT(shefParser.A_FORMATContext ctx) { 
        System.out.println("A Format block: " + ctx.getText());
    }

}
