/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.opendcs.shefit;

import org.antlr.v4.runtime.tree.ErrorNode;
import org.opendcs.shef.parser.shefBaseListener;
import org.opendcs.shef.parser.shefParser;

public class shefListener extends shefBaseListener {
    
    @Override
    public void enterShefFile(shefParser.ShefFileContext ctx) {
        System.out.println("Starting shef file.");
    }

    @Override
    public void enterA_FORMAT(shefParser.A_FORMATContext ctx) {
        System.out.println("Within an A format " + ctx.toStringTree());
    }

    @Override 
    public void exitA_FORMAT(shefParser.A_FORMATContext ctx) { 
    }

    @Override
    public void visitErrorNode(ErrorNode node) {
        System.out.println("Error on : " + node.getText() + ", Tree = " + node.toStringTree());
    }
}
